spring.application.name=GestorFin
spring.datasource.url=jdbc:mysql://gestorfin-pcgamer2207-21c9.c.aivencloud.com:20863/defaultdb?sslMode=REQUIRED&serverTimezone=America/Sao_Paulo
spring.datasource.username=avnadmin
spring.datasource.password=Db password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true